M48
; DRILL file {KiCad 9.0.6} date 2026-04-21T21:20:42+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-21T21:20:42+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.375
%
G90
G05
T1
X6.115Y19.595
X6.115Y13.815
T2
X20.694Y8.79
X21.71Y13.87
X22.726Y8.79
T3
X19.17Y13.87
X19.17Y10.695
X24.25Y13.87
X24.25Y10.695
M30
